source 'https://rubygems.org'
ruby '2.4.4'

gem 'robe', :path => '/users/col/dev/workspace/robe/gems/robe'
# gem 'robe', :git => 'https://github.com/balmoral/robe'

gem 'opal', '~> 0.11.3'
# gem 'opal', :git => 'https://github.com/opal/opal' # 0.11.0.dev

gem 'opal-sprockets', '~> 0.4.1.0.11.0'
# gem 'opal-sprockets', :git => 'https://github.com/opal/opal-sprockets' # 0.11.0.dev

gem 'thin' # or puma

