# opal-browser stuff
require 'opal-browser'
require 'browser/event'
require 'browser/animation_frame'
require 'browser/history'
require 'browser/location'
require 'browser/effects'
# robe stuff
require 'robe/common/trace'
require 'robe/client/browser/opal_browser_ext/patches'
require 'robe/client/browser/opal_browser_ext/window'
require 'robe/client/browser/opal_browser_ext/document'
require 'robe/client/browser/opal_browser_ext/node'
require 'robe/client/browser/opal_browser_ext/element'
require 'robe/client/browser/opal_browser_ext/cookies'
require 'robe/client/browser/opal_browser_ext/bootstrap'
